project:
  type: website

website:
  title: "TNW-OS-support"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EstherPlomp/TNW-OS-support

format:
  html:
    theme: simplex
    css: styles.css

editor: visual

